export const cameraURL = [
  "http://127.0.0.1:5000/video_feed"
  // "https://www.youtube.com/embed/L_d4NglYuVM",
  // "https://www.youtube.com/embed/AJSeaFthdeE",
  // "https://www.youtube.com/embed/RV-6221lNEo",
  // "https://www.youtube.com/embed/y-Dffe1sGAQ",
  // "https://www.youtube.com/embed/ILqfglyQzh4",
  // "https://www.youtube.com/embed/KqK3N7ZOTVc",
  // "https://www.youtube.com/embed/L_d4NglYuVM",
  // "https://www.youtube.com/embed/AJSeaFthdeE",
  // "https://www.youtube.com/embed/RV-6221lNEo",
  // "https://www.youtube.com/embed/y-Dffe1sGAQ",
  // "https://www.youtube.com/embed/ILqfglyQzh4",
  // "https://www.youtube.com/embed/KqK3N7ZOTVc",
  // "https://www.youtube.com/embed/L_d4NglYuVM",
  // "https://www.youtube.com/embed/AJSeaFthdeE",
  // "https://www.youtube.com/embed/RV-6221lNEo",
  // "https://www.youtube.com/embed/y-Dffe1sGAQ",
  // "https://www.youtube.com/embed/ILqfglyQzh4",
  // "https://www.youtube.com/embed/KqK3N7ZOTVc",
  // "https://www.youtube.com/embed/L_d4NglYuVM",
  // "https://www.youtube.com/embed/AJSeaFthdeE",
  // "https://www.youtube.com/embed/RV-6221lNEo",
  // "https://www.youtube.com/embed/y-Dffe1sGAQ",
  // "https://www.youtube.com/embed/ILqfglyQzh4",
  // "https://www.youtube.com/embed/KqK3N7ZOTVc",
  // "https://www.youtube.com/embed/KqK3N7ZOTVc",
];
